name: Create PR from Temporary Branch

on:
  push:
    branches:
      - master
permissions:
  contents: write  
  pull-requests: write  

jobs:
  create-temp-branch-pr:
    if: |
      !contains(github.event.head_commit.message, 'Merge pull request') &&
      github.event.created != true &&
      github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
      - name: Create and push temporary branch
        run: |
          CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          TEMP_BRANCH="temp/${CURRENT_BRANCH}/${TIMESTAMP}"
          
          # Get the current commit SHA
          CURRENT_SHA=$(git rev-parse HEAD)
          
          # Create temp branch but don't switch to it
          git branch $TEMP_BRANCH $CURRENT_SHA
          
          # Push temp branch immediately
          git push origin $TEMP_BRANCH
          
          # Save environment variables
          echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV
          echo "TEMP_BRANCH=$TEMP_BRANCH" >> $GITHUB_ENV
          echo "CURRENT_SHA=$CURRENT_SHA" >> $GITHUB_ENV
          
      - name: Revert changes on original branch
        run: |
          # Make sure we're on the original branch
          git checkout ${{ env.CURRENT_BRANCH }}
          
          # Create revert commit
          git revert --no-edit ${{ env.CURRENT_SHA }}
          
          # Push the revert commit
          git push origin ${{ env.CURRENT_BRANCH }}
          
      - name: Wait for branches to sync
        run: |
          # Give GitHub a moment to process the pushes
          sleep 10
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Restore original changes"
          branch: ${{ env.TEMP_BRANCH }}
          base: ${{ env.CURRENT_BRANCH }}
          title: "Restore changes from ${{ env.CURRENT_BRANCH }} branch"
          body: |
            This PR contains the original changes that were pushed to `${{ env.CURRENT_BRANCH }}`.
            The changes were temporarily moved to this branch and can be restored by merging this PR.
            
            Original commit: ${{ env.CURRENT_SHA }}
          delete-branch: false
