name: Create PR from Temporary Branch

on:
  push:
    branches:
      - master
permissions:
  contents: write  
  pull-requests: write  

jobs:
  create-temp-branch-pr:
    if: |
      !contains(github.event.head_commit.message, 'Merge pull request') &&
      github.event.created != true &&
      github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
      - name: Create temporary branch
        run: |
          CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          TEMP_BRANCH="temp/${CURRENT_BRANCH}/${TIMESTAMP}"
          
          # Get the current commit SHA (the one we want to preserve)
          CURRENT_SHA=$(git rev-parse HEAD)
          
          echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV
          echo "TEMP_BRANCH=$TEMP_BRANCH" >> $GITHUB_ENV
          echo "CURRENT_SHA=$CURRENT_SHA" >> $GITHUB_ENV
          
          # Create a temporary branch from the specific commit
          git push origin $CURRENT_SHA:refs/heads/$TEMP_BRANCH
          
      - name: Create revert commit
        run: |
          # Create revert commit only on the current branch
          git revert --no-edit ${{ env.CURRENT_SHA }}
          git push origin ${{ env.CURRENT_BRANCH }}
          
      - name: Debug branch state
        run: |
          echo "Current branch state:"
          git log -n 2 --oneline ${{ env.CURRENT_BRANCH }}
          
          echo "\nTemp branch state:"
          git ls-remote origin ${{ env.TEMP_BRANCH }}
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.TEMP_BRANCH }}
          base: ${{ env.CURRENT_BRANCH }}
          title: "Restore changes from ${{ env.CURRENT_BRANCH }} branch"
          body: |
            This PR contains the original changes that were pushed to `${{ env.CURRENT_BRANCH }}`.
            The changes were temporarily moved to this branch and can be restored by merging this PR.
            
            Original commit: ${{ env.CURRENT_SHA }}
          delete-branch: false
