name: Create PR from Temporary Branch

on:
  push:
    branches:
      - master
permissions:
  contents: write  
  pull-requests: write  

jobs:
  create-temp-branch-pr:
    if: |
      !contains(github.event.head_commit.message, 'Merge pull request') &&
      github.event.created != true &&
      github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
      - name: Get branch name and create temp branch
        run: |
          CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          TEMP_BRANCH="temp/${CURRENT_BRANCH}/${TIMESTAMP}"
          
          # Store the current commit SHA
          CURRENT_SHA=$(git rev-parse HEAD)
          
          # Create temp branch from the current state
          git checkout -b $TEMP_BRANCH
          
          # Save environment variables
          echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV
          echo "TEMP_BRANCH=$TEMP_BRANCH" >> $GITHUB_ENV
          echo "CURRENT_SHA=$CURRENT_SHA" >> $GITHUB_ENV
          
      - name: Push temporary branch
        run: |
          git push origin ${{ env.TEMP_BRANCH }}
          
      - name: Revert changes on original branch
        run: |
          # Switch back to original branch
          git checkout ${{ env.CURRENT_BRANCH }}
          
          # Create revert commit
          git revert --no-edit ${{ env.CURRENT_SHA }}
          
          # Push the revert commit
          git push origin ${{ env.CURRENT_BRANCH }}

      - name: Checkout temporary branch
        run: git checkout ${{ env.TEMP_BRANCH }}
          
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ env.TEMP_BRANCH }}
          destination_branch: ${{ env.CURRENT_BRANCH }}
          pr_title: "Restore changes from ${{ env.CURRENT_BRANCH }} branch"
          pr_body: |
            This PR contains the original changes that were pushed to `${{ env.CURRENT_BRANCH }}`.
            The changes were temporarily moved to this branch and can be restored by merging this PR.
            
            Original commit: ${{ env.CURRENT_SHA }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
