name: Create PR from Temporary Branch

on:
  push:
    branches:
      - master

permissions:
  contents: write  
  pull-requests: write  

jobs:
  create-temp-branch-pr:
    if: |
      !contains(github.event.head_commit.message, 'Merge pull request') &&
      github.event.created != true &&
      github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
      - name: Get branch name and store commit hash
        run: |
          CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          LAST_COMMIT_HASH=$(git rev-parse HEAD)
          echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV
          echo "LAST_COMMIT_HASH=$LAST_COMMIT_HASH" >> $GITHUB_ENV
          
      - name: Revert last commit in original branch
        run: |
          git checkout ${{ env.CURRENT_BRANCH }}
          git revert HEAD --no-edit
          git push origin ${{ env.CURRENT_BRANCH }}
          
      - name: Create temp branch and cherry-pick commit
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          TEMP_BRANCH="temp/${{ env.CURRENT_BRANCH }}/${TIMESTAMP}"
          git checkout -b $TEMP_BRANCH
          git cherry-pick ${{ env.LAST_COMMIT_HASH }}
          echo "TEMP_BRANCH=$TEMP_BRANCH" >> $GITHUB_ENV
          
      - name: Push temporary branch
        run: |
          git push origin ${{ env.TEMP_BRANCH }}
          
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ env.TEMP_BRANCH }}
          destination_branch: ${{ env.CURRENT_BRANCH }}
          pr_title: "Changes from ${{ env.CURRENT_BRANCH }} branch"
          pr_body: |
            This PR contains changes that were originally pushed to `${{ env.CURRENT_BRANCH }}`.
            Created automatically by GitHub Actions.
          github_token: ${{ secrets.GITHUB_TOKEN }}
